ARG BASE_IMAGE=10.10.10.240/library/teastore-base:latest
FROM ${BASE_IMAGE}
MAINTAINER Chair of Software Engineering <se2-it@informatik.uni-wuerzburg.de>

COPY target/*.war /usr/local/tomcat/webapps/
